image: tetraweb/php
before_script:
    - apt-get update
    - apt-get install zip unzip
    - php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');"
    - php composer-setup.php
    - php -r "unlink('composer-setup.php');"
stages:
    - build
    - test
build:
    stage: build
    script:
        composer update -no-dev
test:
    stage: test
    script:
        php think unit