<?php
/**
 * 菜单生成的seed数组
 * @user Jea杨 (JJonline@JJonline.Cn)
 * @date 2019-02-25 23:46:48
 * @file menu_seed.php
 */
$date_time = date('Y-m-d H:i:s');
return [
    [
        'id' => '1',
        'tag' => 'Dasheboard',
        'name' => '工作台',
        'icon' => 'fa fa-dashboard',
        'url' => 'manage/index/index',
        'parent_id' => '0',
        'is_required' => '1',
        'is_badge' => '1',
        'level' => '1',
        'sort' => '1',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '工作台默认首页',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '2',
        'tag' => 'Article',
        'name' => '图文管理',
        'icon' => 'fa fa-file-text',
        'url' => '',
        'parent_id' => '0',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '1',
        'sort' => '196',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '网站图文管理',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '3',
        'tag' => 'Article_List',
        'name' => '图文管理',
        'icon' => 'fa fa-file-text-o',
        'url' => 'manage/article/list',
        'parent_id' => '2',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '2',
        'sort' => '1',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '网站图文列表：文章列表',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '4',
        'tag' => 'Article_Create',
        'name' => '新增图文',
        'icon' => '',
        'url' => 'manage/article/create',
        'parent_id' => '3',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '1',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '新增图文',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '5',
        'tag' => 'Article_Edit',
        'name' => '编辑图文',
        'icon' => '',
        'url' => 'manage/article/edit',
        'parent_id' => '3',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '2',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '编辑图文',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '6',
        'tag' => 'Article_Delete',
        'name' => '删除图文',
        'icon' => '',
        'url' => 'manage/article/delete',
        'parent_id' => '3',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '3',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '删除图文',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '7',
        'tag' => 'Article_Sort',
        'name' => '快速排序',
        'icon' => '',
        'url' => 'manage/article/sort',
        'parent_id' => '3',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '4',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '图文快速排序',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '8',
        'tag' => 'Article_Prop',
        'name' => '快速设置属性',
        'icon' => '',
        'url' => 'manage/article/property',
        'parent_id' => '3',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '5',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '图文快速设置属性',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '9',
        'tag' => 'Article_Cat',
        'name' => '图文分类',
        'icon' => 'fa fa fa-server',
        'url' => 'manage/article_cat/list',
        'parent_id' => '2',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '2',
        'sort' => '2',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '图文分类管理',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '10',
        'tag' => 'Article_Cat_Create',
        'name' => '新增图文分类',
        'icon' => '',
        'url' => 'manage/article_cat/create',
        'parent_id' => '9',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '1',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '新增图文分类',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '11',
        'tag' => 'Article_Cat_Edit',
        'name' => '编辑图文分类',
        'icon' => '',
        'url' => 'manage/article_cat/edit',
        'parent_id' => '9',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '2',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '编辑图文分类',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '12',
        'tag' => 'Article_Cat_Delete',
        'name' => '删除图文分类',
        'icon' => '',
        'url' => 'manage/article_cat/delete',
        'parent_id' => '9',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '3',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '删除图文分类',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '13',
        'tag' => 'Article_Cat_Sort',
        'name' => '图文分类快速排序',
        'icon' => '',
        'url' => 'manage/article_cat/sort',
        'parent_id' => '9',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '4',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '图文分类快速排序',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '14',
        'tag' => 'Tag_List',
        'name' => '关键词管理',
        'icon' => 'fa fa-tags',
        'url' => 'manage/tag/list',
        'parent_id' => '2',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '2',
        'sort' => '3',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '图文关键词管理',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '15',
        'tag' => 'Tag_Create',
        'name' => '新增关键词',
        'icon' => '',
        'url' => 'manage/tag/create',
        'parent_id' => '14',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '1',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '新增关键词',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '16',
        'tag' => 'Tag_Edit',
        'name' => '编辑关键词',
        'icon' => '',
        'url' => 'manage/tag/edit',
        'parent_id' => '14',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '2',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '编辑关键词',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '17',
        'tag' => 'Tag_Delet',
        'name' => '删除关键词',
        'icon' => '',
        'url' => 'manage/tag/delete',
        'parent_id' => '14',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '3',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '删除关键词',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '18',
        'tag' => 'Tag_Sort',
        'name' => '关键词快速排序',
        'icon' => '',
        'url' => 'manage/tag/sort',
        'parent_id' => '14',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '4',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '关键词快速排序',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '19',
        'tag' => 'Frontend_Member_Manage',
        'name' => '会员管理',
        'icon' => 'fa fa-users',
        'url' => '',
        'parent_id' => '0',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '1',
        'sort' => '197',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '前台会员管理',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '20',
        'tag' => 'Frontend_Member_List',
        'name' => '前台会员管理',
        'icon' => 'fa fa-user-circle-o',
        'url' => 'manage/member/list',
        'parent_id' => '19',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '2',
        'sort' => '1',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '前台会员列表',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '21',
        'tag' => 'Frontend_Member_Create',
        'name' => '新增前台会员',
        'icon' => '',
        'url' => 'manage/member/create',
        'parent_id' => '20',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '1',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '新增前台会员',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '22',
        'tag' => 'Frontend_Member_Edit',
        'name' => '编辑前台会员',
        'icon' => '',
        'url' => 'manage/member/edit',
        'parent_id' => '20',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '2',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '编辑前台会员',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '23',
        'tag' => 'Frontend_Member_Enable',
        'name' => '启用禁用前台会员',
        'icon' => '',
        'url' => 'manage/member/enable',
        'parent_id' => '20',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '3',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '启用禁用前台会员',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '24',
        'tag' => 'Frontend_Member_Level',
        'name' => '会员等级设置',
        'icon' => 'fa fa-level-up',
        'url' => 'manage/member_level/list',
        'parent_id' => '19',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '2',
        'sort' => '2',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '会员等级设置和管理',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '25',
        'tag' => 'Frontend_Member_Level_Create',
        'name' => '新增会员等级',
        'icon' => '',
        'url' => 'manage/member_level/create',
        'parent_id' => '24',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '1',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '新增会员等级',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '26',
        'tag' => 'Frontend_Member_Level_Edit',
        'name' => '编辑会员等级',
        'icon' => '',
        'url' => 'manage/member_level/edit',
        'parent_id' => '24',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '2',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '编辑会员等级',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '27',
        'tag' => 'Frontend_Member_Level_Delete',
        'name' => '删除会员等级',
        'icon' => '',
        'url' => 'manage/member_level/delete',
        'parent_id' => '24',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '3',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '删除会员等级',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '28',
        'tag' => 'Mine',
        'name' => '个人中心',
        'icon' => 'fa fa-h-square',
        'url' => '',
        'parent_id' => '0',
        'is_required' => '1',
        'is_badge' => '0',
        'level' => '1',
        'sort' => '198',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '个人中心',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '29',
        'tag' => 'Mine_Profile',
        'name' => '个人资料概要',
        'icon' => 'fa fa-user-o',
        'url' => 'manage/mine/profile',
        'parent_id' => '28',
        'is_required' => '1',
        'is_badge' => '0',
        'level' => '2',
        'sort' => '1',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '个人中心概要页面',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '30',
        'tag' => 'Mine_Edit',
        'name' => '修改个人资料',
        'icon' => '',
        'url' => 'manage/mine/edit',
        'parent_id' => '29',
        'is_required' => '1',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '1',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '修改个人资料、账号密码等信息',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '31',
        'tag' => 'Common_UploadFile',
        'name' => '上传文件',
        'icon' => '',
        'url' => 'manage/upload/upload',
        'parent_id' => '29',
        'is_required' => '1',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '2',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '上传文件公共权限',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '32',
        'tag' => 'Operation_Record',
        'name' => '查看操作记录',
        'icon' => '',
        'url' => 'manage/operation/record',
        'parent_id' => '29',
        'is_required' => '1',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '3',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '通用的查看各种数据的操作记录接口，非敏感接口通用授权',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '33',
        'tag' => 'Common_Badge',
        'name' => 'Badge统计',
        'icon' => '',
        'url' => 'manage/statistics/badge',
        'parent_id' => '29',
        'is_required' => '1',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '4',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => 'Badge统计：即左侧导航栏后方的badge小标',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '34',
        'tag' => 'Async_Task_Manage',
        'name' => '异步任务列表',
        'icon' => 'fa fa-bookmark-o',
        'url' => 'manage/async_task/list',
        'parent_id' => '28',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '2',
        'sort' => '2',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '查看当前异步任务列表和状态',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '35',
        'tag' => 'Async_Task_Detail',
        'name' => '查看异步任务详情',
        'icon' => '',
        'url' => 'manage/async_task/detail',
        'parent_id' => '34',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '1',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '查看单条异步任务详情',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '36',
        'tag' => 'System_Setting',
        'name' => '系统设置',
        'icon' => 'fa fa-sun-o',
        'url' => '',
        'parent_id' => '0',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '1',
        'sort' => '199',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '系统角色管理、系统参数设置等',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '37',
        'tag' => 'Dept_Manage',
        'name' => '部门管理',
        'icon' => 'fa fa-address-card',
        'url' => 'manage/department/list',
        'parent_id' => '36',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '2',
        'sort' => '1',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '部门列表管理',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '38',
        'tag' => 'Dept_Create',
        'name' => '新增部门',
        'icon' => '',
        'url' => 'manage/department/create',
        'parent_id' => '37',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '1',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '新增部门',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '39',
        'tag' => 'Dept_Edit',
        'name' => '编辑部门',
        'icon' => '',
        'url' => 'manage/department/edit',
        'parent_id' => '37',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '2',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '编辑部门',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '40',
        'tag' => 'Dept_Delete',
        'name' => '删除部门',
        'icon' => '',
        'url' => 'manage/department/delete',
        'parent_id' => '37',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '3',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '删除部门数据',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '41',
        'tag' => 'Dept_Sort',
        'name' => '部门排序',
        'icon' => '',
        'url' => 'manage/department/sort',
        'parent_id' => '37',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '4',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '部门快速排序进行调整',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '42',
        'tag' => 'Role_Manage',
        'name' => '角色管理',
        'icon' => 'fa fa-child',
        'url' => 'manage/role/list',
        'parent_id' => '36',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '2',
        'sort' => '2',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '系统内所有角色列表',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '43',
        'tag' => 'Role_Create',
        'name' => '新增角色',
        'icon' => '',
        'url' => 'manage/role/create',
        'parent_id' => '42',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '1',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '新增角色',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '44',
        'tag' => 'Role_Edit',
        'name' => '编辑角色',
        'icon' => '',
        'url' => 'manage/role/edit',
        'parent_id' => '42',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '2',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '编辑角色',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '45',
        'tag' => 'Role_Delete',
        'name' => '删除角色',
        'icon' => '',
        'url' => 'manage/role/delete',
        'parent_id' => '42',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '3',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '删除角色',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '46',
        'tag' => 'Role_Sort',
        'name' => '角色排序',
        'icon' => '',
        'url' => 'manage/role/sort',
        'parent_id' => '42',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '4',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '快速设置角色排序',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '47',
        'tag' => 'Config_Setting_List',
        'name' => '参数设置',
        'icon' => 'fa fa-check-square-o',
        'url' => 'manage/config/list',
        'parent_id' => '36',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '2',
        'sort' => '5',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '站点各个配置项值设置，与`站点配置`管理侧重点不一样，前者侧重于配置条目本身的新增和修改，后者侧重于配置项的值设置',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '48',
        'tag' => 'Config_Setting_Save',
        'name' => '保存参数设置',
        'icon' => '',
        'url' => 'manage/config/save',
        'parent_id' => '47',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '1',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '提交保存，不给权限可查看而无法修改',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '49',
        'tag' => 'Developer_Tools',
        'name' => 'Developer',
        'icon' => 'fa fa-code',
        'url' => '',
        'parent_id' => '0',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '1',
        'sort' => '200',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '开发者使用的菜单',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '50',
        'tag' => 'Menu_Tools_List',
        'name' => '后台菜单管理',
        'icon' => 'fa fa-venus-double',
        'url' => 'manage/menu/list',
        'parent_id' => '49',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '2',
        'sort' => '1',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '开发者管理权限菜单',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '51',
        'tag' => 'Menu_Tools_Create',
        'name' => '新增菜单',
        'icon' => 'fa fa-plus-square-o',
        'url' => 'manage/menu/create',
        'parent_id' => '50',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '1',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '开发者新增管理菜单',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '52',
        'tag' => 'Menu_Tools_Edit',
        'name' => '编辑菜单',
        'icon' => '',
        'url' => 'manage/menu/edit',
        'parent_id' => '50',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '2',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '编辑修改菜单',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '53',
        'tag' => 'Menu_Tools_Delete',
        'name' => '删除菜单',
        'icon' => '',
        'url' => 'manage/menu/delete',
        'parent_id' => '50',
        'is_required' => '0',
        'is_badge' => '1',
        'level' => '3',
        'sort' => '3',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '删除菜单',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '54',
        'tag' => 'Menu_Tools_Sort',
        'name' => '菜单排序',
        'icon' => '',
        'url' => 'manage/menu/sort',
        'parent_id' => '50',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '4',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '快速设置菜单排序',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '55',
        'tag' => 'Menu_Reorganize',
        'name' => '重整菜单',
        'icon' => '',
        'url' => 'manage/menu/reorganize',
        'parent_id' => '50',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '5',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '重新按菜单层级、排序整理菜单数据并生成seed数据',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '56',
        'tag' => 'Admin_User_List',
        'name' => '后台用户管理',
        'icon' => 'fa fa-users',
        'url' => 'manage/user/list',
        'parent_id' => '49',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '2',
        'sort' => '4',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '后台用户列表管理，非管理权限禁止分配',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '57',
        'tag' => 'Admin_User_Create',
        'name' => '新增用户',
        'icon' => '',
        'url' => 'manage/user/create',
        'parent_id' => '56',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '1',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '新增后台用户',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '58',
        'tag' => 'Admin_User_Edit',
        'name' => '编辑用户',
        'icon' => '',
        'url' => 'manage/user/edit',
        'parent_id' => '56',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '2',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '编辑后台管理员用户信息',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '59',
        'tag' => 'Admin_User_Enable',
        'name' => '启用和禁用用户',
        'icon' => '',
        'url' => 'manage/user/enabletoggle',
        'parent_id' => '56',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '3',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '启用和禁用后台管理员',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '60',
        'tag' => 'Site_Config',
        'name' => '站点配置管理',
        'icon' => 'fa fa-sun-o',
        'url' => 'manage/site_config/list',
        'parent_id' => '49',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '2',
        'sort' => '5',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '站点配置项增删改查，与`参数设置`管理侧重点不一样，前者侧重于配置项的值设置，后者侧重于配置条目本身的新增和修改',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '61',
        'tag' => 'Site_Config_Create',
        'name' => '新增配置项目',
        'icon' => '',
        'url' => 'manage/site_config/create',
        'parent_id' => '60',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '1',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '新增站点配置项目',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '62',
        'tag' => 'Site_Config_Edit',
        'name' => '编辑配置项目',
        'icon' => '',
        'url' => 'manage/site_config/edit',
        'parent_id' => '60',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '2',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '编辑配置项目',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '63',
        'tag' => 'Site_Config_Delete',
        'name' => '删除配置项目',
        'icon' => '',
        'url' => 'manage/site_config/delete',
        'parent_id' => '60',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '3',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '删除配置项目',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
    [
        'id' => '64',
        'tag' => 'Site_Config_Sort',
        'name' => '配置项目快速排序',
        'icon' => '',
        'url' => 'manage/site_config/sort',
        'parent_id' => '60',
        'is_required' => '0',
        'is_badge' => '0',
        'level' => '3',
        'sort' => '4',
        'extra_param' => null,
        'is_system' => '1',
        'is_permissions' => '0',
        'is_column' => '0',
        'remark' => '配置项目快速排序',
        'create_time' => $date_time,
        'update_time' => $date_time,
    ],
];
